server:
  port: 8989
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/admin
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/com/baizhi/mapper/*.xml